name: Test Code
on: [pull_request, workflow_dispatch]

jobs:
  unittest:
    runs-on: windows-2019
    steps:
      - name: Checkout the source branch of the PR
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name}}
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Start server
        run: npm run serve
      - name: Run tests
        run: npm run test
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with: 
          name: screenshots 
          path: ./screenshots # path is listed in package.json's test task
          